spring:
  config:
    import: application-secrets.properties
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: ${LOCAL_DATABASE_URL}
    username: ${LOCAL_DATABASE_USERNAME}
    password: ${LOCAL_DATABASE_PASSWORD}

  h2:
    console:
      enabled: true
      path: ${LOCAL_DATABASE_CONSOLE_URL}

  sql:
    init:
      mode: always
